### PR TITLE
Adding "Tests in DiSTAF" to 3.8 community roadmap page in glusterweb

### PR DESCRIPTION
**Pull request by msvbhat**
Signed-off-by: M S Vishwanath Bhat msvbhat@gmail.com

### CODE REVIEW

**Comment by nixpanic** [comment]
Sorry MS, you have to update this again after I merged the [restructured version](https://www.gluster.org/community/roadmap/3.8/).

**Comment by msvbhat** [comment]
@nixpanic I went through the restructured version, and looks like all features have the field 'DiSTAF Testcase'. So since we have that, do we need to have a separate feature 'Tests in DiSTAF'?

If you think it makes sense, I can send the updated patch.

**Comment by nixpanic** [comment]
Yes, I think it is important to not that we are running regular DiSTAF tests. I added "Periodic DiSTAF testing" under "Miscellaneous Enhancements", but if you think it should better be under "Eco-system" you can move it there.

**Comment by msvbhat** [comment]
Yes, I think tests are part of eco-system and not a miscellaneous enhancement. I will close this PR and send a separate PR for that now.

**Pull request closed without merging**
